# Generated by Django 6.0.3 on 2026-04-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_backgroundmusic_alter_productset_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productset',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайктардын саны'),
        ),
    ]
