# Generated by Django 6.0.3 on 2026-04-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productset_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Кардар')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('product_title', models.CharField(max_length=200, verbose_name='Топтом')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Кошумча маалымат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Заказ түшкөн убакыт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказдар',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кардардын аты')),
                ('message', models.TextField(verbose_name='Пикири')),
                ('stars', models.PositiveIntegerField(choices=[(1, '1 Жылдыз'), (2, '2 Жылдыз'), (3, '3 Жылдыз'), (4, '4 Жылдыз'), (5, '5 Жылдыз')], default=5, verbose_name='Баасы (Жылдыз)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жазылган убактысы')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Сайтта көрсөтүлсүнбү?')),
            ],
            options={
                'verbose_name': 'Пикир',
                'verbose_name_plural': 'Пикирлер',
                'ordering': ['-created_at'],
            },
        ),
    ]
