# Generated by Django 6.0.3 on 2026-04-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_review_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Пикир', 'verbose_name_plural': 'Пикирлер'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='backgroundmusic',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Азыр ойнолсунбу?'),
        ),
        migrations.AlterField(
            model_name='backgroundmusic',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Музыканын аталышы'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Кошулган убактысы'),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайктар'),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(verbose_name='Пикирдин тексти'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=5, verbose_name='Жылдыз саны'),
        ),
    ]
