# Generated by Django 6.0.3 on 2026-04-15 19:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delete_order_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_reply',
            field=models.TextField(blank=True, null=True, verbose_name='Админдин жообу'),
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Кардардын сүрөтү'),
        ),
    ]
